<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ms_sysextending"
 *
 * Auto generated by Extension Builder 2013-04-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ms_sysextending',
	'description' => '',
	'category' => 'module',
	'author' => 'mediasapiens.co',
	'author_email' => 'dev@mediasapiens.co',
	'author_company' => 'mediasapiens',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>