<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ms_slider"
 *
 * Auto generated by Extension Builder 2013-04-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
  'title' => 'Slider',
  'description' => '',
  'category' => 'plugin',
  'author' => 'ms',
  'author_email' => 'dev@mediasapiens.co',
  'author_company' => 'mediasapiens',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'alpha',
  'internal' => '',
  'uploadfolder' => '1',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '',
  'constraints' => array(
    'depends' => array(
      'extbase' => '6.0',
      'fluid' => '6.0',
      'typo3' => '6.0',
    ),
    'conflicts' => array(
    ),
    'suggests' => array(
    ),
  ),
);

?>